spec_version: 5.0.0
type: app
name: speed-rec-dataquality
title: Speed Recommendations Data Quality
description: Send speed recommendations if data quality metrics are above thresholds
version: 1.0.11
flags:
  enable_runtime_update:
    configuration: false
    parameters: true
    resources: false
    resource_properties: true
data_streams:
  inputs:
    - name: data_quality
      data_type: number
    - name: speed
      data_type: number
    - name: casing_pressure
      data_type: number
    - name: tubing_pressure
      data_type: number
  outputs: []
control_changes:
  inputs: []
  outputs:
    - name: motor_speed_set_point
      data_type: number
custom_actions:
  inputs: []
  outputs: []
parameters:
  - name: kelvin_closed_loop
    data_type: boolean
  - name: dataquality_min_threshold
    data_type: number
ui_schemas:
  parameters: ui_schemas/parameters.json
defaults:
  configuration: {}
  parameters:
    kelvin_closed_loop: false
    dataquality_min_threshold: 59
  system: {}
