spec_version: 5.0.0
type: app
name: voltage-app
title: Voltage Anomaly Detection
description: This is a hello app for demonstration purposes.
version: 1.0.1
flags:
  enable_runtime_update:
    configuration: false
    parameters: true
    resources: false
    resource_properties: true
data_streams:
  inputs:
    - name: motor_temperature
      data_type: number
    - name: motor_speed
      data_type: number
  outputs: []
control_changes:
  inputs: []
  outputs:
    - name: motor_speed_set_point
      data_type: number
custom_actions:
  inputs: []
  outputs: []
parameters:
  - name: kelvin_closed_loop
    data_type: boolean
  - name: temperature_max_threshold
    data_type: number
ui_schemas:
  parameters: ui_schemas/parameters.json
defaults:
  configuration: {}
  parameters:
    kelvin_closed_loop: false
    temperature_max_threshold: 59
  system: {}
